version: '2'

services:
  mysql1:
    image: mysql:5.7.22
    container_name: mysql1
    tty: true
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      # - MYSQL_ROOT_PASSWORD="root"
    volumes:
      - ./mysql5.7.22/my1.cnf:/etc/mysql/my.cnf
      - ./data/mysql1:/var/lib/mysql

  mysql2:
    image: mysql:5.7.22
    container_name: mysql2
    tty: true
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    #   - MYSQL_ROOT_PASSWORD="root"
    depends_on:
      - mysql1
    volumes:
      - ./mysql5.7.22/my2.cnf:/etc/mysql/my.cnf
      - ./data/mysql2:/var/lib/mysql

  centos7:
    build: centos7
    container_name: centos7
    tty: true
    working_dir: /centos7
    depends_on:
      - mysql1
      - mysql2
    volumes:
       - ./scenarios:/mounted/scenarios
       - ./actions:/mounted/actions
       - ./backups:/mounted/backups
