version: '2'

services:
  # maria1:
  #   image: mariadb:10.0.30
  #   container_name: maria1
  #   tty: true
  #   ports:
  #     - "33071:3306"
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
  #     # - MYSQL_ROOT_PASSWORD="root"
  #   volumes:
  #     - ./data/maria1:/var/lib/mysql
  #     - ./maria10.4.8/my1.cnf:/etc/my.cnf

  mysql1:
    image: mysql:5.7.22
    container_name: mysql1
    tty: true
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      # - MYSQL_ROOT_PASSWORD="root"
    volumes:
      - ./mysql5.7.22/my1.cnf:/etc/mysql/my.cnf
      - ./data/mysql1:/var/lib/mysql

  mysql2:
    image: mysql:5.7.22
    container_name: mysql2
    tty: true
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    #   - MYSQL_ROOT_PASSWORD="root"
    depends_on:
      - mysql1
    volumes:
      - ./mysql5.7.22/my2.cnf:/etc/mysql/my.cnf
      - ./data/mysql2:/var/lib/mysql

  mysql3:
    image: mysql:5.7.22
    container_name: mysql3
    tty: true
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    #   - MYSQL_ROOT_PASSWORD="root"
    depends_on:
      - mysql2
    volumes:
      - ./mysql5.7.22/my3.cnf:/etc/mysql/my.cnf
      - ./data/mysql3:/var/lib/mysql

  executor:
    build: executor
    container_name: executor
    tty: true
    working_dir: /mounted
    depends_on:
      - mysql1
      - mysql2
      - mysql3
    volumes:
       - ./scenarios:/mounted/scenarios
       - ./actions:/mounted/actions
       - ./backups:/mounted/backups
