DROP DATABASE IF EXISTS dba;
CREATE DATABASE dba CHARACTER SET latin1;

USE dba;
DROP TABLE IF EXISTS x;
CREATE TABLE x (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(200) DEFAULT NULL,
  original varchar(200) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


