
CHANGE MASTER TO
    MASTER_HOST='mysql1',
    MASTER_USER='rep_user',
    MASTER_PASSWORD='rep_user',
 	MASTER_LOG_POS=495,
    MASTER_LOG_FILE='mysql-bin.000008',
    MASTER_PORT=3306;

RESET SLAVE;
START SLAVE;

DROP USER IF EXISTS 'nonroot'@'%';
CREATE USER 'nonroot'@'%' IDENTIFIED BY 'nonroot';
GRANT ALL PRIVILEGES ON dba.* TO 'nonroot'@'%';

FLUSH PRIVILEGES;
